
apiVersion: v1
kind: Secret
metadata:
  name: portfolioservice-secret
type: Opaque
data:
  SECRET_KEY: ZGV2X3NlY3JldF9rZXk=  # base64 for "dev_secret_key"
  POSTGRES_PASSWORD: ZGV2X3Bhc3N3b3Jk  # base64 for "dev_password"
  REDIS_PASSWORD: cmVkaXNwYXNz  # base64 for "redispass"
